name: az - tenant level deployment

on:
  push:
    branches-ignore:
      - main
    paths:
        - 'tenantLevel/**'
        - '.github/workflows/template-tenantLevel.yml'
        - '.github/workflows/main-tenantLevel.yml'

  pull_request_target:
    types:
      - closed
    paths:
      - 'tenantLevel/**'
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main') || 
        github.ref != 'refs/heads/main'
    uses: ./.github/workflows/template-tenantLevel.yml
    with:
      managementGroupHierarchy: test
    secrets: inherit

  prod:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') ||
         github.event.pull_request.merged == true
    uses: ./.github/workflows/template-tenantLevel.yml
    with:
      managementGroupHierarchy: prod
    secrets: inherit