name: az - BigBang

on:
  workflow_dispatch:
    inputs:
      managementGroupHierarchy:
        description: 'Management Group Hierarchy'
        required: true
        default: 'test'
        type: choice
        options:
          - 'test'
          - 'prod'

permissions:
  id-token: write
  contents: read

jobs:
  gitHub:
    uses: ./.github/workflows/template-gitHub.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit

  tenantLevel:
    needs: gitHub
    uses: ./.github/workflows/template-tenantLevel.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit

  identity:
    needs: tenantLevel
    uses: ./.github/workflows/template-Identity.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit

  monitoring:
    needs: tenantLevel
    uses: ./.github/workflows/template-monitoring.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit

  policy:
    needs: 
      - identity
      - monitoring
    uses: ./.github/workflows/template-policy.yml
    with:
      managementGroupHierarchy: ${{ github.event.inputs.managementGroupHierarchy }}
    secrets: inherit