name: template - Policy

on:
  workflow_call:
    inputs:
        environment:
          required: true
          type: string
        customDefinitionsTemplateFile:
          default: ./policy/bicep/main-definitions.bicep
          type: string
        assignmentsTemplateFile:
          default: ./policy/bicep/main-assignments.bicep
          type: string
        deploymentNameForAssignments:
            default: policyAssignments
            type: string

jobs:
    definitions:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}-azurePlatform
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ vars.APP_AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: Deploy policies
          uses: azure/cli@v1
          with:
              inlineScript: |
                deployment=$(az stack mg create \
                --name policyDefinitions \
                --management-group-id ${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
                --location ${{  vars.AZURE_DEFAULT_LOCATION }} \
                --template-file ${{ inputs.customDefinitionsTemplateFile }} \
                --parameters ./policy/parameters/customDefinitions.bicepparam \
                --deny-settings-mode None \
                --action-on-unmanage deleteAll \
                --yes)
    online:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}-azurePlatform
        env:
          deploymentScope: online
        needs: definitions
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ vars.APP_AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: Deploy policies
          uses: azure/cli@v1
          with:
              inlineScript: |
                deployment=$(az stack mg create \
                --name ${{ inputs.deploymentNameForAssignments }} \
                --management-group-id ${{ env.deploymentScope }}-${{ inputs.environment }} \
                --location ${{  vars.AZURE_DEFAULT_LOCATION }} \
                --template-file ${{ inputs.assignmentsTemplateFile }} \
                --parameters ./policy/parameters/${{ env.deploymentScope }}.bicepparam \
                --parameters location=${{  vars.AZURE_DEFAULT_LOCATION }} \
                --parameters identityResoruceId=${{  vars.POLICY_RESOURCE_ID }} \
                --parameters environment=${{ inputs.environment }} \
                --parameters topLevelManagementGroupName=${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
                --deny-settings-mode None \
                --action-on-unmanage deleteAll \
                --yes)

    platform:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}-azurePlatform
        env:
          deploymentScope: platform
        needs: definitions
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ vars.APP_AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: policies-platform
          uses: azure/cli@v1
          with:
              inlineScript: |
                deployment=$(az stack mg create \
                --name ${{ inputs.deploymentNameForAssignments }} \
                --management-group-id ${{ env.deploymentScope }}-${{ inputs.environment }} \
                --location ${{  vars.AZURE_DEFAULT_LOCATION }} \
                --template-file ${{ inputs.assignmentsTemplateFile }} \
                --parameters ./policy/parameters/${{ env.deploymentScope }}.bicepparam \
                --parameters location=${{  vars.AZURE_DEFAULT_LOCATION }} \
                --parameters identityResoruceId=${{  vars.POLICY_RESOURCE_ID }} \
                --parameters environment=${{ inputs.environment }} \
                --parameters topLevelManagementGroupName=${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
                --deny-settings-mode None \
                --action-on-unmanage deleteAll \
                --yes)
                
    playground:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}-azurePlatform
        env:
          deploymentScope: playground
        needs: definitions
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ vars.APP_AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: policies-platform
          uses: azure/cli@v1
          with:
              inlineScript: |
                deployment=$(az stack mg create \
                --name ${{ inputs.deploymentNameForAssignments }} \
                --management-group-id ${{ env.deploymentScope }}-${{ inputs.environment }} \
                --location ${{  vars.AZURE_DEFAULT_LOCATION }} \
                --template-file ${{ inputs.assignmentsTemplateFile }} \
                --parameters ./policy/parameters/${{ env.deploymentScope }}.bicepparam \
                --parameters location=${{  vars.AZURE_DEFAULT_LOCATION }} \
                --parameters identityResoruceId=${{  vars.POLICY_RESOURCE_ID }} \
                --parameters environment=${{ inputs.environment }} \
                --parameters topLevelManagementGroupName=${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
                --deny-settings-mode None \
                --action-on-unmanage deleteAll \
                --yes)


