name: template - Identity

on:
  workflow_call:
    inputs:
        managementGroupHierarchy:
          required: true
          type: string

jobs:
    managedIdentities:
        runs-on: ubuntu-latest
        environment: ${{ inputs.managementGroupHierarchy }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: get github token
          id: github-token
          uses: actions/create-github-app-token@v1
          with:
            app-id: ${{ vars.APP_GITHUB_BIGBANG_ID }}
            private-key: ${{ secrets.APP_GITHUB_BIGBANG }}
            owner: ${{ github.repository_owner }}

        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: managedIdentities
          uses: azure/cli@v2
          with:
            inlineScript: |
              az account set --subscription ${{ vars.MANAGEMENT_SUBSCRIPTION_ID }}

              deployment=$(az stack mg create \
                --name identity \
                --location ${{ vars.AZURE_DEFAULT_LOCATION }} \
                --management-group-id ${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
                --template-file './Identity/bicep/managedIdentities.bicep' \
                --parameters './Identity/parameters/AzureIdentity.bicepparam' \
                --parameters subscriptionId=${{ vars.MANAGEMENT_SUBSCRIPTION_ID }} \
                --parameters environment=${{ inputs.managementGroupHierarchy }} \
                --parameters location=${{  vars.AZURE_DEFAULT_LOCATION }} \
                --deny-settings-mode None \
                --action-on-unmanage deleteAll \
                --yes)

              envVariables=$(echo $deployment | jq '.outputs.gitHubEnviromentVariables.value')
              echo "Deployment Outputs: $envVariables"
              echo "managedIdentities=$(echo $envVariables | jq -c .)" >> $GITHUB_ENV
         
        - name: set env variables
          env:
            GH_TOKEN: ${{ steps.github-token.outputs.token }}
          run: |
              deploymentOutputs=$(echo $managedIdentities | jq .)
              echo "Deployment Outputs: $deploymentOutputs"
              
              objects=$(echo $deploymentOutputs | jq -c '.[]')
              for obj in $objects; do
                keys=$(echo $obj | jq -r 'keys[]')
                for key in $keys; do
                  value=$(echo $obj | jq --arg k "$key" -r '.[$k]')
                  gh variable set $key \
                    --body "$value" \
                    --env ${{ inputs.managementGroupHierarchy }} \
                    -R "${{ github.repository_owner }}/AzurePlatform"
                done
              done
       
    roleAssignments:
      runs-on: ubuntu-latest
      environment: ${{ inputs.managementGroupHierarchy }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ vars.AZURE_PLATFORM_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID}}
            allow-no-subscriptions: true
            enable-AzPSSession: false

        - name: entraGroups
          uses: azure/cli@v2
          with:
            inlineScript: |
              deployment=$(az deployment mg create \
                --name RBAC \
                --location ${{ vars.AZURE_DEFAULT_LOCATION }} \
                --management-group-id ${{ vars.TOP_LEVEL_MANAGEMENTGROUP_NAME }} \
                --template-file './Identity/bicep/rbac.bicep' \
                --parameters './Identity/parameters/rbac.bicepparam' \
                --parameters azurePlatformTestPrincipalId=${{ vars.AZURE_PLATFORM_TEST_PRINCIPAL_ID }} \
                --parameters environment=${{ inputs.managementGroupHierarchy }})

              envVariables=$(echo $deployment | jq '.outputs.gitHubEnviromentVariables.value')
              echo "Deployment Outputs: $envVariables"
              echo "RBAC=$(echo $envVariables | jq -c .)" >> $GITHUB_ENV